"""Create a new log-parser fixture package from CI or user-provided logs.

When a log is supplied (--log-file or --stdin), the parser runs automatically
and populates expected.json and metadata.json with real inferred values.
Without a log, blank scaffolding is written for manual completion.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# Allow running from anywhere inside the ai_engine tree.
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from app.services.log_analyzer import parse_log


ROOT = Path(__file__).resolve().parents[1] / "services" / "fixtures"


def _slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def _infer_language_and_framework(raw_log: str) -> tuple[str, str, float]:
    """Mirror the inference logic from main.py so metadata stays consistent."""
    lowered = raw_log.lower()
    if any(t in lowered for t in ("traceback", "pytest", "assertionerror", "modulenotfounderror")):
        return "python", "pytest", 0.88
    if any(t in lowered for t in ("jest", "vitest", "npm err!", "typeerror:")):
        return "node", "jest", 0.78
    if any(t in lowered for t in ("--- fail:", "panic:", "go test")):
        return "go", "go test", 0.82
    if any(t in lowered for t in ("caused by:", "exception in thread", "mvn test", "gradle")):
        return "java", "maven", 0.80
    if any(t in lowered for t in ("cargo test", "panicked at", "error[e")):
        return "rust", "cargo", 0.81
    return "unknown", "unknown", 0.35


def _confidence_band(score: float) -> str:
    if score >= 0.80:
        return "high"
    if score >= 0.60:
        return "medium"
    return "low"


def create_fixture(
    name: str,
    source: str,
    raw_log: str | None,
    language: str = "unknown",
    framework: str = "unknown",
) -> Path:
    fixture_name = _slugify(name)
    fixture_dir = ROOT / fixture_name
    fixture_dir.mkdir(parents=True, exist_ok=False)

    log_content = raw_log if raw_log else "# Paste raw CI or user-provided test logs here.\n"
    (fixture_dir / "input.log").write_text(log_content, encoding="utf-8")

    if raw_log:
        # Auto-populate from the real parser output.
        parsed = parse_log(raw_log)
        inferred_lang, inferred_fw, confidence = _infer_language_and_framework(raw_log)
        # CLI overrides take precedence over inference.
        final_lang = language if language != "unknown" else inferred_lang
        final_fw = framework if framework != "unknown" else inferred_fw
        notes = "Auto-generated by create_log_fixture.py — review and adjust before committing."
        band = _confidence_band(confidence)

        expected = {
            "error_type": parsed["error_type"],
            "failing_test": parsed["failing_test"],
            "stack_trace_lines": parsed["stack_trace_lines"],
            "error_signature": parsed["error_signature"],
        }
    else:
        final_lang, final_fw, band = language, framework, "low"
        notes = "Fill expected.json after validating parser output."
        expected = {
            "error_type": "UnknownError",
            "failing_test": "unknown",
            "stack_trace_lines": [],
            "error_signature": "UnknownError | unknown | no message",
        }

    (fixture_dir / "expected.json").write_text(
        json.dumps(expected, indent=2) + "\n", encoding="utf-8"
    )
    (fixture_dir / "metadata.json").write_text(
        json.dumps(
            {
                "name": fixture_name,
                "source": source,
                "language": final_lang,
                "framework": final_fw,
                "expected_confidence_band": band,
                "notes": notes,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    return fixture_dir


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--name", required=True, help="Fixture name")
    parser.add_argument(
        "--source",
        choices=("ci", "user"),
        default="user",
        help="Log source",
    )
    parser.add_argument("--language", default="unknown", help="Override inferred language")
    parser.add_argument("--framework", default="unknown", help="Override inferred framework")
    parser.add_argument(
        "--log-file",
        type=Path,
        default=None,
        help="Path to raw log file — triggers auto-population",
    )
    parser.add_argument(
        "--stdin",
        action="store_true",
        help="Read raw log from stdin — triggers auto-population",
    )

    args = parser.parse_args()

    raw_log: str | None = None
    if args.stdin:
        raw_log = sys.stdin.read()
    elif args.log_file:
        raw_log = args.log_file.read_text(encoding="utf-8")

    created = create_fixture(
        name=args.name,
        source=args.source,
        raw_log=raw_log,
        language=args.language,
        framework=args.framework,
    )
    print(created)


if __name__ == "__main__":
    main()
